#! /usr/bin/env python
import os,sys
def createDir(dirName):
    try:
        os.mkdir(os.getcwd()+"/"+dirName)
    except:
        print("Directory "+os.getcwd()+"/"+dirName+" already exists")


def toolInstaller(toolName):
    createDir(toolName+"/Installation")
    with open(os.path.abspath("/usr/local/lib/jenkinsPluginGenFiles/")+"/$TOOL+INSTALLER.txt", "rt") as txtInstaller:
        with open(os.getcwd()+"/"+toolName+"/Installation/"+toolName+'Installer.java', "wt") as javaInstaller:
            for line in txtInstaller:
                javaInstaller.write(line.replace('$TOOL+INSTALLER', toolName+'Installer'))


def toolInstallation(toolName):
    toolInstaller(toolName)
    with open(os.path.abspath("/usr/local/lib/jenkinsPluginGenFiles/")+"/$TOOL+INSTALLATION.txt", "rt") as txtInstallation:
        with open(os.getcwd()+"/"+toolName+"/Installation/"+toolName+'Tool.java', "wt") as javaInstallation:
            for line in txtInstallation:
                if '$TOOL+NAME' in line:
                    javaInstallation.write(line.replace('$TOOL+NAME', toolName))
                else:
                    javaInstallation.write(line.replace('$TOOL+INSTALLATION',toolName+'Tool'))     
    

def toolUtil(toolName):
    createDir(toolName+"/util")
    with open(os.path.abspath("/usr/local/lib/jenkinsPluginGenFiles/")+"/$TOOL+UTIL.txt", "rt") as txtUtil:
        with open(os.getcwd()+"/"+toolName+"/util/"+toolName+'Util.java', "wt") as javaUtil:
            for line in txtUtil:
                javaUtil.write(line.replace('$TOOL+UTIL', toolName+'Util'))


def toolBuilder(toolName):
    with open(os.path.abspath("/usr/local/lib/jenkinsPluginGenFiles/")+"/$TOOL+BUILDER.txt", "rt") as txtBuilder:
        with open(os.getcwd()+"/"+toolName+"/"+toolName+'Builder.java', "wt") as javaBuilder:
            for line in txtBuilder:
                if "$TOOL+UTIL" in line:
                    javaBuilder.write(line.replace('$TOOL+UTIL', toolName+'Util')) 
                else:    
                    javaBuilder.write(line.replace('$TOOL+BUILDER', toolName+'Builder'))


def toolWrapper(toolName):
    with open(os.path.abspath("/usr/local/lib/jenkinsPluginGenFiles/")+"/$TOOL+WRAPPER.txt", "rt") as txtWrapper:
        with open(os.getcwd()+"/"+toolName+"/"+toolName+'Wrapper.java', "wt") as javaWrapper:
            for line in txtWrapper:
                if "$TOOL+INSTALLATION" in line:
                    javaWrapper.write(line.replace('$TOOL+INSTALLATION',toolName+'Tool'))
                elif "$TOOL+UTIL" in line:
                    javaWrapper.write(line.replace('$TOOL+UTIL', toolName+'Util'))
                else:
                    javaWrapper.write(line.replace('$TOOL+WRAPPER', toolName+'Wrapper')) 


def toolPublisher(toolName):
    with open(os.path.abspath("/usr/local/lib/jenkinsPluginGenFiles/")+"/$TOOL+PUBLISHER.txt", "rt") as txtPublisher:
        with open(os.getcwd()+"/"+toolName+"/"+toolName+'Publisher.java', "wt") as javaPublisher:
            for line in txtPublisher:
                javaPublisher.write(line.replace('$TOOL+PUBLISHER', toolName+'Publisher'))            


def all(toolName):
    toolInstallation(toolName)
    toolWrapper(toolName)
    toolBuilder(toolName)
    toolPublisher(toolName)
    toolUtil(toolName)

def help():
    print "usage: jen {--name} [options ...]"
    print "     --name       :the tool name"
    print "options:"
    print "     -a           :creates it all - used by default"
    print "     -b           :creates build step"
    print "     -i           :creates tool-installation & installer"
    print "     -p           :creates post-build action"
    print "     -u           :creates utility class with helpful methods"
    print "     -w           :creates wrapper - build environment"
    print "     -h, --help   :call help and exit"

def checkArgv(argv,toolName):
    commandsAndToolName = [__file__,"-h","--help","--name","-a","-b","-i","-p","-u","-w",toolName]
    for i in argv:
        if i not in commandsAndToolName:
            print i + " - command not found."
            exit(help())


def main():
    if len(sys.argv) == 2 and ("-h" in sys.argv or "--help" in sys.argv):
        exit(help())

    if "--name" not in sys.argv:
        print "Error: --name is not inserted"
        exit(help())
    
    try:
        pluginName = sys.argv[sys.argv.index("--name") + 1]
        if '-' in pluginName:
            print "Error: --name is not inserted"
            exit(help())
    except IndexError:
        print "Error: --name is not inserted"
        exit(help())
    
    isValid = False
    checkArgv(sys.argv,pluginName)

    try:
        int(pluginName)
    except ValueError:
        isValid = True

    if isValid:
        createDir(pluginName) 
    else:
        exit("Need to enter a vaild name - exiting now")

    if len(sys.argv) == 3:
        all(pluginName)

    if "-a" in sys.argv:
        all(pluginName)
    
    if "-b" in sys.argv:
        toolBuilder(pluginName)
    
    if "-i" in sys.argv:
        toolInstallation(pluginName)

    if "-p" in sys.argv:
        toolPublisher(pluginName)

    if "-u" in sys.argv:
        toolUtil(pluginName)

    if "-w" in sys.argv:
        toolWrapper(pluginName)
    
    if "-h" in sys.argv or "--help" in sys.argv:
        exit(help())

if __name__ == "__main__":
    main()